server:
  port: 9000

spring:
  application:
    name: gateway-service
## Config repo ##
  config:
    enabled: false
    import: optional:configserver:http://root:pass@localhost:8888
## Gateway cfg ##
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: product-route
          uri: http://localhost:8080
          predicates[0]: Path=/catalog/**

## EUREKA ##
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
