server:
  port: 8080

spring:
  application:
    name: product-service
  profiles:
    active: dev
## Config repo ##
  config:
    import: optional:configserver:http://root:pass@localhost:8888

## circuitbreaker exceptions ##
resilience4j.circuitbreaker:
  configs:
    default:
      recordExceptions:
        - feign.FeignException
        - com.example.productservice.exception.IdNotValidException