
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: info, health

spring:
  application:
    name: config-service
  profiles:
    active: git
  security:
    basic:
      enabled: true
    user:
      name: root
      password: pass
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ka5ta/config-repo

## EUREKA ##
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/